DROP TABLE IF EXISTS "etudiants" CASCADE;
DROP TABLE IF EXISTS "dates" CASCADE;
DROP TABLE IF EXISTS "voitures" CASCADE;
DROP TABLE IF EXISTS "voyages" CASCADE;
DROP TABLE IF EXISTS "avis" CASCADE;
DROP TABLE IF EXISTS "villes" CASCADE;
DROP TABLE IF EXISTS "reservations" CASCADE;
DROP TABLE IF EXISTS "destinations" CASCADE;

-- DROP FUNCTION IF EXISTS "nom fonction";