DROP TABLE IF EXISTS "avis" CASCADE;
DROP TABLE IF EXISTS "reservations" CASCADE;
DROP TABLE IF EXISTS "voyages" CASCADE;
DROP TABLE IF EXISTS "etapes" CASCADE;
DROP TABLE IF EXISTS "villes" CASCADE;
DROP TABLE IF EXISTS "voitures" CASCADE;
DROP TABLE IF EXISTS "etudiants" CASCADE;
DROP TYPE IF EXISTS "confirmation";

-- DROP FUNCTION IF EXISTS "nom fonction";