INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Pierson','Louis','lpierson002@enseirb-matmeca.fr','lpierson002','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Vernant','Charlène','cvernant@enseirb-matmeca.fr','cvernant','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Durand','Arthur','adurand@enseirb-matmeca.fr','adurand','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Bastien','Hugo','hbastien@enseirb-matmeca.fr','hbastien','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Vachet','Léo','lvachet@enseirb-matmeca.fr','lvachet','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Bonnet','Lilian','lbonnet005@enseirb-matmeca.fr','lbonnet005','2004-10-19 10:23:54');
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Peugeot','208','Citadine','Gris','Très bon état',' ', 1);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Twingo','Citadine','Bleu','Très bon état',' ', 2);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','R5','Collection','Blanc','Dans son jus','Penser à fermer la vitre avec les mains', 5);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Clio Campus 2','Citadine','Bleu Kangoo','Embrayage fatigué','Ambiance', 6);
