INSERT INTO voitures (marque, typ, couleur, etat, divers, id_etudiant) VALUES ('Peugeot','208','Citadine','Gris','Très bon etat',' ', 0);
INSERT INTO voitures (marque, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Twingo','Citadine','Bleu','Très bon etat',' ', 1);
INSERT INTO voitures (marque, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','R5','Collection','Blanc','Dans son jus','Penser à fermer la vitre avec les mains', 2);
INSERT INTO voitures (marque, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Clio Campus','Citadine','Bleu Kangoo','Embrayage fatigue','Ambiance', 3);
INSERT INTO voitures (marque, modele, type, couleur, etat, divers, id_etudiant) VALUES ('Peugeot','208','Citadine','Gris','Très bon etat',' ', 0);
INSERT INTO voitures (marque, modele, type, couleur, etat, divers, id_etudiant) VALUES ('Renault','Twingo','Citadine','Bleu','Très bon etat',' ', 1);
INSERT INTO voitures (marque, modele, type, couleur, etat, divers, id_etudiant) VALUES ('Renault','R5','Collection','Blanc','Dans son jus','Penser à fermer la vitre avec les mains', 2);
INSERT INTO voitures (marque, modele, type, couleur, etat, divers, id_etudiant) VALUES ('Renault','Clio Campus','Citadine','Bleu Kangoo','Embrayage fatigue','Ambiance', 3);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Peugeot','208','Citadine','Gris','Très bon etat',' ', 0);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Twingo','Citadine','Bleu','Très bon etat',' ', 1);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','R5','Collection','Blanc','Dans son jus','Penser à fermer la vitre avec les mains', 2);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Clio Campus','Citadine','Bleu Kangoo','Embrayage fatigue','Ambiance', 3);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Peugeot','208','Citadine','Gris','Très bon état',' ', );
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Twingo','Citadine','Bleu','Très bon état',' ', );
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','R5','Collection','Blanc','Dans son jus','Penser à fermer la vitre avec les mains', );
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Clio Campus','Citadine','Bleu Kangoo','Embrayage fatigue','Ambiance', );
