INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Pierson','Louis','lpierson002@enseirb-matmeca.fr','lpierson002','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Vernant','Charlène','cvernant@enseirb-matmeca.fr','cvernant','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Durand','Arthur','adurand@enseirb-matmeca.fr','adurand','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Bastien','Hugo','hbastien@enseirb-matmeca.fr','hbastien','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Vachet','Léo','lvachet@enseirb-matmeca.fr','lvachet','2004-10-19 10:23:54');
INSERT INTO etudiants (nom, prenom, mail, mot_de_passe, date_de_naissance) VALUES ('Bonnet','Lilian','lbonnet005@enseirb-matmeca.fr','lbonnet005','2004-10-19 10:23:54');
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Peugeot','208','Citadine','Gris','Très bon état',' ', 2);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Twingo','Citadine','Bleu','Très bon état',' ', 1);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','R5','Collection','Blanc','Dans son jus','Penser à fermer la vitre avec les mains', 5);
INSERT INTO voitures (marque, modele, typ, couleur, etat, divers, id_etudiant) VALUES ('Renault','Clio Campus 2','Tout Terrain','Bleu Kangoo','Embrayage fatigué','Ambiance', 6);
INSERT INTO villes (nom) VALUES ('Paris');
INSERT INTO villes (nom) VALUES ('Marseille');
INSERT INTO villes (nom) VALUES ('Lyon');
INSERT INTO villes (nom) VALUES ('Toulouse');
INSERT INTO villes (nom) VALUES ('Nice');
INSERT INTO villes (nom) VALUES ('Nantes');
INSERT INTO villes (nom) VALUES ('Strasbourg');
INSERT INTO villes (nom) VALUES ('Montpellier');
INSERT INTO villes (nom) VALUES ('Bordeaux');
INSERT INTO villes (nom) VALUES ('Lille');
INSERT INTO villes (nom) VALUES ('Rennes');
INSERT INTO villes (nom) VALUES ('Reims');
INSERT INTO villes (nom) VALUES ('Le Havre');
INSERT INTO villes (nom) VALUES ('Saint-Étienne');
INSERT INTO villes (nom) VALUES ('Toulon');
INSERT INTO villes (nom) VALUES ('Grenoble');
INSERT INTO villes (nom) VALUES ('Dijon');
INSERT INTO villes (nom) VALUES ('Nîmes');
INSERT INTO villes (nom) VALUES ('Angers');
INSERT INTO villes (nom) VALUES ('Villeurbanne');
INSERT INTO villes (nom) VALUES ('Le Mans');
INSERT INTO villes (nom) VALUES ('Saint-Denis (La Réunion)');
INSERT INTO villes (nom) VALUES ('Aix-en-Provence');
INSERT INTO villes (nom) VALUES ('Clermont-Ferrand');
INSERT INTO villes (nom) VALUES ('Brest');
INSERT INTO villes (nom) VALUES ('Limoges');
INSERT INTO villes (nom) VALUES ('Tours');
INSERT INTO villes (nom) VALUES ('Amiens');
INSERT INTO villes (nom) VALUES ('Perpignan');
INSERT INTO villes (nom) VALUES ('Metz');
INSERT INTO villes (nom) VALUES ('Besançon');
INSERT INTO villes (nom) VALUES ('Boulogne-Billancourt');
INSERT INTO villes (nom) VALUES ('Orléans');
INSERT INTO villes (nom) VALUES ('Mulhouse');
INSERT INTO villes (nom) VALUES ('Rouen');
INSERT INTO villes (nom) VALUES ('Saint-Denis');
INSERT INTO villes (nom) VALUES ('Caen');
INSERT INTO villes (nom) VALUES ('Argenteuil');
INSERT INTO villes (nom) VALUES ('Saint-Paul (La Réunion)');
INSERT INTO villes (nom) VALUES ('Montreuil');
INSERT INTO villes (nom) VALUES ('Nancy');
INSERT INTO villes (nom) VALUES ('Roubaix');
INSERT INTO villes (nom) VALUES ('Tourcoing');
INSERT INTO villes (nom) VALUES ('Nanterre');
INSERT INTO villes (nom) VALUES ('Avignon');
INSERT INTO villes (nom) VALUES ('Vitry-sur-Seine');
INSERT INTO villes (nom) VALUES ('Créteil');
INSERT INTO villes (nom) VALUES ('Dunkerque');
INSERT INTO villes (nom) VALUES ('Poitiers');
INSERT INTO villes (nom) VALUES ('Asnières-sur-Seine');
INSERT INTO villes (nom) VALUES ('Courbevoie');
INSERT INTO villes (nom) VALUES ('Versailles');
INSERT INTO villes (nom) VALUES ('Colombes');
INSERT INTO villes (nom) VALUES ('Fort-de-France');
INSERT INTO villes (nom) VALUES ('Aulnay-sous-Bois');
INSERT INTO villes (nom) VALUES ('Saint-Pierre (La Réunion)');
INSERT INTO villes (nom) VALUES ('Rueil-Malmaison');
INSERT INTO villes (nom) VALUES ('Pau');
INSERT INTO villes (nom) VALUES ('Aubervilliers');
INSERT INTO villes (nom) VALUES ('Le Tampon');
INSERT INTO villes (nom) VALUES ('Champigny-sur-Marne');
INSERT INTO villes (nom) VALUES ('Antibes');
INSERT INTO villes (nom) VALUES ('Béziers');
INSERT INTO villes (nom) VALUES ('La Rochelle');
INSERT INTO villes (nom) VALUES ('Saint-Maur-des-Fossés');
INSERT INTO villes (nom) VALUES ('Cannes');
INSERT INTO villes (nom) VALUES ('Calais');
INSERT INTO villes (nom) VALUES ('Saint-Nazaire');
INSERT INTO villes (nom) VALUES ('Mérignac');
INSERT INTO villes (nom) VALUES ('Drancy');
INSERT INTO villes (nom) VALUES ('Colmar');
INSERT INTO villes (nom) VALUES ('Ajaccio');
INSERT INTO villes (nom) VALUES ('Bourges');
INSERT INTO villes (nom) VALUES ('Issy-les-Moulineaux');
INSERT INTO villes (nom) VALUES ('Levallois-Perret');
